version: '3'

services:
  mariadb:
    image: guillaumedupuy/mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - .env
    networks:
      - backend_network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  wordpress:
    image: guillaumedupuy/wordpress:latest
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
      - frontend_network
      - backend_network

networks:
  frontend_network:
  backend_network:

volumes:
  db_data: